server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka

spring:
  application:
    name: api-gateway

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  cloud:
    gateway:
      routes:
        - id: user-status-check
          uri: lb://user-service
          predicates:
            - Path=/user-service/users/status/check
            - Method=GET
            - Header=Authorization, Bearer (.*)
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user-service/users
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}

        - id: user-service-login
          uri: lb://user-service
          predicates:
            - Path=/user-service/users/login
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}

        - id: user-service-get-update-delete
          uri: lb://user-service
          predicates:
            - Path=/user-service/users/**
            - Method=GET,PUT,DELETE
            - Header=Authorization, Bearer (.*)
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment
            - AuthorizationHeaderFilter

token:
  secret: fg3gks23412aqqeqw123222q2az23100000