server:
  port: 0

spring:
  application:
    name: account-management-service

  devtools:
    restart:
      enabled: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: 2355

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka

