server:
  port: ${PORT:0}

spring:
  application:
    name: user-service

  devtools:
    restart:
      enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.aplication.instance_id:${random.value}}