server:
  port: 8012

spring:
  application:
    name: config-server

  profiles:
    active: native

  cloud:
    config:
      server:
        git:
          uri: https://github.com/erhancnlc/micro-service-configuration
          username: erhancnlc
          password: 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
          clone-on-start: true
          default-label: main

        native:
          search-locations: file://${user.home}/dev

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: 2375

management:
  endpoints:
    web:
      exposure:
        include: busrefresh